name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Node Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Flutter Dependencies
        run: flutter pub get
        working-directory: admin
        
      - name: Build Flutter Web App
        run: flutter build web --release --no-tree-shake-icons --base-href /admin/
        working-directory: admin

      - name: Combine Builds
        run: |
          mkdir -p dist/admin
          cp -r admin/build/web/* dist/admin/
        
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOT_LAB_21910 }}'
          channelId: live
          projectId: bot-lab-21910
